### ISSUE TITLE
Set up readthedocs

### ISSUE THREAD

**Issue by wsnoble** [freejstone/open_groupwalk#5]
I think we need documentation hosted at https://readthedocs.org/

For example, I am looking at the output file and wondering what all the columns mean. 

```
winning_scores	labels	delta_mass	winning_peptides	rank	database	scan	file	all_group_ids	q_vals
```

I think "winning_scores" should be "score," and similarly "winning_peptides" should be "peptide."

"q_vals" should be "q_value"

I don't know what "labels" means, nor "all_group_ids".

**Comment by freejstone** [comment]
Closing now since documentation is now properly hosted.
